name: Test Workflow

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3.3.0
      - id: setup_nodejs
        name: Setup node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '14.x'
      - id: npm_ci
        name: npm ci
        run: npm ci
      - id: npm_test
        name: Test
        run: npm test
      - id: npm_build
        name: Build
        run: npm run build
